repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0  # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
  - id: docformatter
    # args: ["--in-place", "--blank", "--pre-summary-newline", "-r"]
    args: ["--in-place", "--blank", "-r"]
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    files: ^experimenttools/
    args: ["--convention=numpy"]
